spring.application.name=Gliders Web System

#spring.datasource.driver-class-name=org.postgresql.Driver
##spring.datasource.url=jdbc:postgresql://database:5432/${POSTGRES_DB}
#spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.hikari.initialization-fail-timeout=60000
#spring.datasource.hikari.connection-timeout=20000

# H2 is a test database that runs on mem and starts with the app
# good when there is no need for a real database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# flyway
spring.flyway.enabled=false

# dev
spring.jpa.hibernate.ddl-auto=update
# prod spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
